#    _    _                 _ _   _
#   / \  | | __ _  ___ _ __(_) |_| |_ _   _
#  / _ \ | |/ _` |/ __| '__| | __| __| | | |
# / ___ \| | (_| | (__| |  | | |_| |_| |_| |
#/_/   \_\_|\__,_|\___|_|  |_|\__|\__|\__, |
#                                     |___/

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 14.00

#[font.bold]
#family = "JetBrainsMono Nerd Font"
#style = "Bold"

#[font.bold_italic]
#family = "JetBrainsMono Nerd Font"
#style = "Bold Italic"

#[font.italic]
#family = "JetBrainsMono Nerd Font"
#style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "SemiBold"




[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
opacity = 0.8
title = "Alacritty"


[colors.cursor]
cursor = "#acb0d0"
text = "CellBackground"


[colors.selection]
background = "#3e4451" 
text = "CellForeground"


[colors.primary]
background = "#11121D"
#background = "#1D2021"
#foreground = "#b9f27c"
#foreground = "#acb0d0"
foreground  = "#ffb86c"
[env]
TERM = "xterm-256color"

[window.class]
general = "Alacritty"
instance = "Alacritty"

#[window.padding]
#x = 6
#y = 6

#Tokyo Night normal
[colors.normal]
      black =   '#32344a'
      red   =   '#f7768e'
      green =   '#9ece6a'
      yellow =  '#e0af68'
      blue  = 	'#7aa2f7'
      magenta = '#ad8ee6'
      cyan =    '#449dab'
      white =   '#787c99'

    # Bright colors
[colors.bright]   
      black =   '#444b6a'
      red   =   '#ff7a93'
      green =   '#b9f27c'
      yellow =  '#ff9e64'
      blue =    '#7da6ff'
      magenta = '#bb9af7'
      cyan =    '#0db9d7'
      white =   '#acb0d0'


#Dracula Theme
#[colors.normal]
#black  =	"#282a36" 		
#white =	"#f8f8f2" 	
#blue =		"#6272a4"
#yellow =	"#ffb86c"
#magenta =	"#bd93f9" 

#Dracula Theme Bright
#[colors.bright]
#black =		"#44475a"
#cyan  =		"#8be9fd" 	
#green =		"#50fa7b" 		
#magenta  =	"#ff79c6" 		 	
#red  =		"#ff5555" 	 	
#yellow =	"#f1fa8c"



