# ____  _                 _     _
#/ ___|| |_ __ _ _ __ ___| |__ (_)_ __
#\___ \| __/ _` | '__/ __| '_ \| | '_ \
# ___) | || (_| | |  \__ \ | | | | |_) |
#|____/ \__\__,_|_|  |___/_| |_|_| .__/
#                                |_|

[username]
style_user="bold"
style_root = "bold"
format = "($style) "
disabled = false
show_always = true



[character]                            # The name of the module we are configuring is "character"
success_symbol = "[ ](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red)"



#  
# configure directory
[directory]
read_only = "  "
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
#style = "bold blue"


[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
stashed = "[${count}*](green)" 
modified = "[${count}+](yellow)" 
deleted =  "[${count}-](red)" 
conflicted =  "[${count}~](red)" 
ahead = "⇡${count}"
behind = "⇣${count}"
untracked = "[${count}?](blue)" 
staged = "[${count}+](green)" 


[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[haskell]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = " "

[nodejs]
symbol = "󰎙 "




